import {Card} from './card';

export const CARDS: Card[] = [
    {id: 1, vrednost: 1, tip: 'Herc', linkSlike: '../assets/PNG/1H.png'},
    {id: 2, vrednost: 2, tip: 'Herc', linkSlike: '../assets/PNG/2H.png' },
    {id: 3, vrednost: 3, tip: 'Herc', linkSlike: '../assets/PNG/3H.png' },
    {id: 4, vrednost: 4, tip: 'Herc', linkSlike: '../assets/PNG/4H.png' },
    {id: 5, vrednost: 5, tip: 'Herc', linkSlike: '../assets/PNG/5H.png' },
    {id: 6, vrednost: 6, tip: 'Herc', linkSlike: '../assets/PNG/6H.png' },
    {id: 7, vrednost: 7, tip: 'Herc', linkSlike: '../assets/PNG/7H.png' },
    {id: 8, vrednost: 8, tip: 'Herc', linkSlike: '../assets/PNG/8H.png' },
    {id: 9, vrednost: 9, tip: 'Herc', linkSlike: '../assets/PNG/9H.png' },
    {id: 10, vrednost: 10, tip: 'Herc', linkSlike: '../assets/PNG/10H.png' },
    {id: 11, vrednost: 12, tip: 'Herc', linkSlike: '../assets/PNG/JH.png' },
    {id: 12, vrednost: 13, tip: 'Herc', linkSlike: '../assets/PNG/QH.png' },
    {id: 13, vrednost: 14, tip: 'Herc', linkSlike: '../assets/PNG/KH.png' },
    {id: 14, vrednost: 1, tip: 'Karo', linkSlike: '' },
    {id: 15, vrednost: 2, tip: 'Karo', linkSlike: '' },
    {id: 16, vrednost: 3, tip: 'Karo', linkSlike: ''  },
    {id: 17, vrednost: 4, tip: 'Karo', linkSlike: ''  },
    {id: 18, vrednost: 5, tip: 'Karo', linkSlike: ''  },
    {id: 19, vrednost: 6, tip: 'Karo', linkSlike: ''  },
    {id: 20, vrednost: 7, tip: 'Karo', linkSlike: ''  },
    {id: 21, vrednost: 8, tip: 'Karo', linkSlike: ''  },
    {id: 22, vrednost: 9, tip: 'Karo', linkSlike: ''  },
    {id: 23, vrednost: 10, tip: 'Karo', linkSlike: ''  },
    {id: 24, vrednost: 12, tip: 'Karo', linkSlike: ''  },
    {id: 25, vrednost: 13, tip: 'Karo', linkSlike: ''  },
    {id: 26, vrednost: 14, tip: 'Karo', linkSlike: ''  },
    {id: 27, vrednost: 1, tip: 'Tref', linkSlike: ''  },
    {id: 28, vrednost: 2, tip: 'Tref', linkSlike: ''  },
    {id: 29, vrednost: 3, tip: 'Tref', linkSlike: ''  },
    {id: 30, vrednost: 4, tip: 'Tref', linkSlike: ''  },
    {id: 31, vrednost: 5, tip: 'Tref', linkSlike: ''  },
    {id: 32, vrednost: 6, tip: 'Tref', linkSlike: ''  },
    {id: 33, vrednost: 7, tip: 'Tref', linkSlike: ''  },
    {id: 34, vrednost: 8, tip: 'Tref', linkSlike: ''  },
    {id: 35, vrednost: 9, tip: 'Tref', linkSlike: ''  },
    {id: 36, vrednost: 10, tip: 'Tref', linkSlike: ''  },
    {id: 37, vrednost: 12, tip: 'Tref', linkSlike: ''  },
    {id: 38, vrednost: 13, tip: 'Tref', linkSlike: ''  },
    {id: 39, vrednost: 14, tip: 'Tref', linkSlike: ''  },
    {id: 40, vrednost: 1, tip: 'Pik', linkSlike: ''  },
    {id: 41, vrednost: 2, tip: 'Pik', linkSlike: ''  },
    {id: 42, vrednost: 3, tip: 'Pik', linkSlike: ''  },
    {id: 43, vrednost: 4, tip: 'Pik', linkSlike: ''  },
    {id: 44, vrednost: 5, tip: 'Pik', linkSlike: ''  },
    {id: 45, vrednost: 6, tip: 'Pik', linkSlike: ''  },
    {id: 46, vrednost: 7, tip: 'Pik', linkSlike: ''  },
    {id: 47, vrednost: 8, tip: 'Pik', linkSlike: ''  },
    {id: 48, vrednost: 9, tip: 'Pik', linkSlike: ''  },
    {id: 49, vrednost: 10, tip: 'Pik', linkSlike: ''  },
    {id: 50, vrednost: 12, tip: 'Pik', linkSlike: ''  },
    {id: 51, vrednost: 13, tip: 'Pik', linkSlike: ''  },
    {id: 52, vrednost: 14, tip: 'Pik', linkSlike: ''  }
];